jwt:
  secret: jbItEsmX1xvI7OQp9LeKLP2sAkwj6ZFDVa7ZgxtECnDp729tZniBCQlWlZnQPGxa6p2fiaqBh7fVhkKacC2RCsWAfWmwx2ingPA8/GRvsXwUYIzPtbJQ+GO9QZuc2k/cKhDhz93zO+8Yfr/pqHvowhssgM6jT+Sq3dMFJt1Ooh8DzPhqP4500UKepoM6GNTdfob0uAwQnjQg4Poxztc/XpCAsHfoG0LaOfIbhHy+kTbXI17kVvpTJDLYzjQgjE3G8Kg10RVGRHVEXJZCGQDhLY/31+0d6voS+xwhbsndXpzEcmnUEK0B3MAOahlk4EV5sAgNf85jwQMlNm+Ww+go/Zixsktc0iJC9L0sKqXr1xTdDplxcPQjoYXVJ0iIlqT49RwNwnOkOBXd+miMcVmRUE2ZC2fmEXwDvl8+Wz9sIZ7iEAOdHZBDVNUDDQ57iRJPOtUiXfx8zwFD2wB1Ix/DwJTR+Vvmq/Joc8TYRmQoREwdP9hHhrPE2UBwzh/KDtkEfwXUxrzBOZ28etH3RueiSXvrIeMHmSuUKEjmD8857zHLL+01ZUThMii9Z0J1C35UasdzveaFgAOZEcM3O0JN5+fc0DZsE4LPURxLa5lhiq2InKqhWpwHvUxLMKZ6/xoyoE/bGaqm4TOxBIMqJvonZi3o3+gi70lB9K7xcPg66EEAfxiCPwir1jPyYStq7tm9
  expirationMs: 86400000

server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: demodb123
    url: jdbc:postgresql://localhost:5432/fmanager
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
#     ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true